#端口号
server:
  port: 8337


dubbo:
  application:            #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
    name: order_mgr_provide
  registry:                 #注册中心配置，用于配置连接注册中心相关信息。
    address: zookeeper://127.0.0.1:2181
  metadata-report:
    address: zookeeper://127.0.0.1:2181
  protocol:     #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受。
    name: dubbo
    port: "20900"
  version: 1.0.0
  scan:
    base-packages: com.sutong.**.impl  #服务暴露与发现消费所在的packag


#Mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mybatis/**/*.xml

#Spring配置
spring:
  jackson:
      default-property-inclusion: non_null
  datasource:
    url: jdbc:db2://172.20.53.34:60000/BJCLEAR1
    username: merchant
    password: merchant@091411
    driver-class-name: com.ibm.db2.jcc.DB2Driver

