#端口号
server:
  port: 8335

#dubbo配置
dubbo:
  application:            #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
    name: pay_provide
  registry:                 #注册中心配置，用于配置连接注册中心相关信息。
    address: zookeeper://127.0.0.1:2181
  metadata-report:
    address: zookeeper://127.0.0.1:2181
  protocol:     #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受。
    name: dubbo
    port: "20889"
  version: 1.0.0
  scan:
    base-packages: com.sutong.**.impl  #服务暴露与发现消费所在的package

#Mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mybatis/**/*.xml

#Spring配置
spring:
  datasource:
    url: jdbc:db2://172.20.53.34:60000/BJCLEAR1
    username: merchant
    password: merchant@091411
    driver-class-name: com.ibm.db2.jcc.DB2Driver
  jackson:
    default-property-inclusion: non_null

#短信接口
sms:
  ip: "http://192.168.1.31:8305/"
  mothed: "sms_Send"
  SOAPActionURI: "http://tempuri.org/sms_Send"
  Namespace: "http://tempuri.org/"
  ChannelID: "40"

#发行接口
issue:
  clientIp: 172.20.53.103
  sessionKey: 0b9486484d6c9aaf2f737a6cfc4e9be2
  url: http://172.20.53.136:38080/
